/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as catWifHatSol from "./CatWifHat.sol";
export type { catWifHatSol };
import type * as catWifHatMaketplaceSol from "./CatWifHatMaketplace.sol";
export type { catWifHatMaketplaceSol };
export type { CatWifHatNFT } from "./CatWifHatNFT";
