/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { Address } from "./Address";
export type { CatWifhat } from "./CatWifhat";
export type { ERC20 } from "./ERC20";
export type { IERC1155Errors } from "./IERC1155Errors";
export type { IERC20 } from "./IERC20";
export type { IERC20Errors } from "./IERC20Errors";
export type { IERC20Metadata } from "./IERC20Metadata";
export type { IERC20Permit } from "./IERC20Permit";
export type { IERC721Errors } from "./IERC721Errors";
export type { IUniswapV2Factory } from "./IUniswapV2Factory";
export type { IUniswapV2Router01 } from "./IUniswapV2Router01";
export type { IUniswapV2Router02 } from "./IUniswapV2Router02";
export type { Ownable } from "./Ownable";
export type { SafeERC20 } from "./SafeERC20";
